image: cprov/stoq:stable

services:
    - postgres:9.5

variables:
  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # Fetch utils/ submodule
  GIT_SUBMODULE_STRATEGY: recursive
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: ""
  STOQLIB_TEST_HOSTNAME: "postgres"
  STOQLIB_TEST_DBNAME: "test"
  STOQLIB_TEST_USERNAME: "test"
  STOQLIB_TEST_PASSWORD: ""

stages:
  - test
  - build

before_script:
  - python3 -V
    # Some tests assume the timezone is America/Sao_Paulo. This can go away if we remove the old nfe
    # plugin
  - ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
  - dpkg-reconfigure --frontend noninteractive tzdata
  - apt-get --yes update
    # Some dependencies for our tests
  - apt-get --yes install xvfb libxml2-utils poppler-utils
    # Remove this once the docker image has jwt installed
  - apt-get --yes install python3-jwt python3-docutils
  - virtualenv -p python3 --system-site-packages venv
  - source venv/bin/activate
  - pip3 install -Ur requirements-test.txt
  - ln -s $PWD/venv/bin/pyflakes $PWD/venv/bin/pyflakes3

test:
  stage: test
  script:
    - xvfb-run make coverage

build_dist:
  stage: build
  script:
    - python setup.py sdist
    - python setup.py bdist_wheel

  artifacts:
    paths:
      - dist
